/*============================================================================*/
/*   Script File                                                              */
/*                                                                            */
/*   Date    : 15-des-2009                                                    */
/*   Creator : Albert                                                          */
/*   Descrip.: Desenvolupament per crear clients al crm   */
/*============================================================================*/
execute procedure s_ajustes ('CRM',017,'Modulo CRM');
commit Work;


ALTER TABLE CRM_CONTACTOS ADD FORMA_DE_PAGO_IMP FORMAS_DE_PAGO;
commit work;
ALTER TABLE CRM_CONTACTOS ADD CLI_PROV_IMP TITULOS_40_NULL;
commit work;
ALTER TABLE CRM_CONTACTOS ADD ID_AGENTE CONTADORES;
commit work;
ALTER TABLE CRM_CONTACTOS ADD EMPRESA EMPRESAS;
commit work;
ALTER TABLE CRM_TMP_IMPORTAR_CONTACTOS ADD CLI_PROV_IMP TITULOS_40_NULL;
commit work;
ALTER TABLE CRM_TMP_IMPORTAR_CONTACTOS ADD FORMA_PAGO_IMP FORMAS_DE_PAGO;
commit work;
ALTER TABLE CRM_TMP_IMPORTAR_CONTACTOS ADD ORIGEN_IMP TIPOS_MOVIMIENTOS;
commit work;



DROP VIEW CRM_VER_CONTACTOS;
CREATE VIEW CRM_VER_CONTACTOS(
    EMPRESA,
    ID_CONTACTO,
    NUM_CONTACTO,
    FECHA_ALTA,
    TERCERO,
    NOMBRE_R_SOCIAL,
    NOMBRE_COMERCIAL,
    NOMBRE_CORTO,
    TIPO_RAZON,
    NIF,
    TELEFONO01,
    TELEFONO02,
    TELEFAX,
    DIR_NOMBRE,
    DIR_LOCALIDAD,
    ID_LOCAL,
    EMAIL,
    WEB,
    NOTAS,
    COMENTARIO,
    CLIENTE,
    RUTA_IMAGEN,
    ORIGEN_CONTACTO,
    LINK_GOOGLE,
    ACTIVITAT_ECONOMICA,
    AMBITO,
    TITULO,
    CODPOSTAL,
    PROVINCIA,
    PAIS,
    ID_AGENTE,
    DESC_AGENTE,
    CLI_PROV_IMP,
    FORMA_DE_PAGO_IMP)
AS
SELECT
     CON.EMPRESA,CON.ID_CONTACTO , CON.NUM_CONTACTO , CON.FECHA_ALTA , CON.TERCERO , CON.NOMBRE_R_SOCIAL , CON.NOMBRE_COMERCIAL ,
     CON.NOMBRE_CORTO , TIPO_RAZON ,CON.NIF ,CON.TELEFONO01 ,CON.TELEFONO02 ,CON.TELEFAX , CON.DIR_NOMBRE , CON.DIR_LOCALIDAD ,
     CON.ID_LOCAL , CON.EMAIL , CON.WEB , CON.NOTAS , CON.COMENTARIO ,CON.CLIENTE , CON.RUTA_IMAGEN ,CON.ORIGEN_CONTACTO ,
     CON.LINK_GOOGLE ,CON.ACTIVITAT_ECONOMICA ,CON.AMBITO,LOC.TITULO AS LOCALIDAD,LOC.CODPOSTAL,LOC.PROVINCIA,LOC.PAIS,
     CON.id_agente, VER.titulo, con.cli_prov_imp,con.forma_de_pago_imp
     FROM CRM_CONTACTOS CON
     left join VER_LOCALIDADES LOC ON (CON.DIR_LOCALIDAD=LOC.LOCALIDAD)
     left join VER_AGENTES ver ON (con.empresa=ver.empresa and con.id_agente=ver.agente)
;
SET TERM ^ ;

CREATE TRIGGER CRM_VER_CONTACTOS_BD0 FOR CRM_VER_CONTACTOS
ACTIVE BEFORE DELETE POSITION 0
AS
begin
    delete from crm_contactos
    where (id_contacto = old.id_contacto);
end
^

SET TERM ; ^

SET TERM ^ ;

CREATE TRIGGER CRM_VER_CONTACTOS_BI0 FOR CRM_VER_CONTACTOS
ACTIVE BEFORE INSERT POSITION 0
as
begin
    insert into crm_contactos(
     ID_CONTACTO , NUM_CONTACTO , FECHA_ALTA , TERCERO , NOMBRE_R_SOCIAL , NOMBRE_COMERCIAL ,
     NOMBRE_CORTO , TIPO_RAZON ,NIF ,TELEFONO01 ,TELEFONO02 ,TELEFAX , DIR_NOMBRE , DIR_LOCALIDAD ,
     ID_LOCAL , EMAIL , WEB , NOTAS , COMENTARIO ,CLIENTE , RUTA_IMAGEN ,ORIGEN_CONTACTO ,
     LINK_GOOGLE ,ACTIVITAT_ECONOMICA ,AMBITO,CLI_PROV_IMP,FORMA_DE_PAGO_IMP,ID_AGENTE,EMPRESA)
    values(
     new.ID_CONTACTO , new.NUM_CONTACTO , new.FECHA_ALTA , new.TERCERO , new.NOMBRE_R_SOCIAL , new.NOMBRE_COMERCIAL ,
     new.NOMBRE_CORTO , new.TIPO_RAZON ,new.NIF ,new.TELEFONO01 ,new.TELEFONO02 ,new.TELEFAX , new.DIR_NOMBRE , new.DIR_LOCALIDAD ,
     new.ID_LOCAL , new.EMAIL , new.WEB , new.NOTAS , new.COMENTARIO ,new.CLIENTE , new.RUTA_IMAGEN ,new.ORIGEN_CONTACTO ,
     new.LINK_GOOGLE ,new.ACTIVITAT_ECONOMICA ,new.AMBITO,new.CLI_PROV_IMP,new.FORMA_DE_PAGO_IMP,new.id_agente,
     new.empresa);

   end
^

SET TERM ; ^

SET TERM ^ ;

CREATE TRIGGER CRM_VER_CONTACTOS_BU0 FOR CRM_VER_CONTACTOS
ACTIVE BEFORE UPDATE POSITION 0
as
begin
UPDATE CRM_CONTACTOS
SET
  TELEFONO01=new.TELEFONO01
  ,TELEFONO02=new.TELEFONO02
  ,TELEFAX=new.TELEFAX
  ,DIR_NOMBRE=new.DIR_NOMBRE
  ,DIR_LOCALIDAD=new.DIR_LOCALIDAD
  ,ID_LOCAL=new.ID_LOCAL
  ,EMAIL=new.EMAIL
  ,WEB=new.WEB
  ,NOTAS=new.NOTAS
  ,NUM_CONTACTO=new.NUM_CONTACTO
  ,TERCERO=new.TERCERO
  ,NOMBRE_R_SOCIAL=new.NOMBRE_R_SOCIAL
  ,NOMBRE_COMERCIAL=new.NOMBRE_COMERCIAL
  ,NOMBRE_CORTO=new.NOMBRE_CORTO
  ,FECHA_ALTA=new.FECHA_ALTA
  ,TIPO_RAZON=new.TIPO_RAZON
  ,NIF=new.NIF
  ,COMENTARIO=new.COMENTARIO
  ,CLIENTE=new.CLIENTE
  ,ORIGEN_CONTACTO=new.ORIGEN_CONTACTO
  ,LINK_GOOGLE=new.LINK_GOOGLE
  ,AMBITO=new.AMBITO
  ,ACTIVITAT_ECONOMICA=new.ACTIVITAT_ECONOMICA
  ,CLI_PROV_IMP=new.CLI_PROV_IMP
  ,FORMA_DE_PAGO_imp=new.forma_de_pago_imp
  ,ID_AGENTE=new.id_agente
WHERE
  ID_CONTACTO=new.ID_CONTACTO;

end
^

SET TERM ; ^
commit work;